### ISSUE TITLE
PM08 Comments

### ISSUE THREAD

**Issue by jjgiesey** [Milligan-Engineering/EENG-INVENTORY#8]
Please look at PM08_Comments branch and start incorporating suggestions. Will talk more about them tomorrow.

**Comment by jjgiesey** [comment]
Remaining issues from PM08
// Create a standard header stdafx.h for all files to use.
// Still want to see that you can use a non-default constructor here.
// Need to give preconditions and postconditions for functions. Put these at the declaration.
// Going to need a full set of accessors (get) and mutators (set)

**Comment by SAMWEHNER** [comment]
complete
